version: "3.8"
services:
  mongodb:
    image: "mongo"
    volumes:
      - data:/data/db
  
  mongo-seed:
    build: ./mongo-seed
    depends_on:
      - mongodb
  
  backend:
    build: ./server
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
  
  frontend:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/app/src/
    stdin_open: true
    tty: true
    depends_on:
      - backend
volumes:
  data:
  logs: